version: '3.4'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: video
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
  ms-recommendation-api:
    image: ms-recommendation-api:latest
    container_name: ms-recommendation-api
    ports:
      - 8082:8082
    depends_on:
      - postgresql
    hostname: ms-recommendation-api
    restart: always
    user: root
