apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-recommendation-api-deployment
  labels:
    app: ms-recommendation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-recommendation-api-gateway
  template:
    metadata:
      labels:
        app: ms-recommendation-api-gateway
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
        - name: ms-recommendation-api
          image: ms-recommendation-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          volumeMounts:
            - mountPath: /app/logs
              name: logs
      volumes:
        - name: nginx-conf
          configMap:
            name: ms-recommendation-api-nginx-conf
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pv-claim
